version: "3.9"
services:
  user-service-db:
    container_name: user-service-mariadb
    image: mariadb:10.4
    restart: always
    ports:
      - "33334:3306"
    volumes:
      - ~/docker-repo/userservice:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=userservice
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci