application:
  id: user-service-api
  version: 1.0

server:
#  port: 0 # random
  port: 9001

spring:
  application:
    name: user-service1
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블을 생성 application 실행 시점에
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mariadb://localhost:33334/userservice?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    root: info
    org.hibernate.SQL: debug # hibernate 생성하는 로그 레벨을 debug 로 출력 함.
    org.hibernate.type: trace # parameter log printing 해준다.

eureka:
  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.applicaton.instance_id:${random.value}}
  client:
    register-with-eureka: true # eureka registry 등록 여부
    fetch-registry: true # registry에 있는 정보를 가져올지 여부
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to my user service!