server:
#  port: 0 # random
  port: 9001

spring:
  application:
    name: user-service1
eureka:
  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.applicaton.instance_id:${random.value}}
  client:
    register-with-eureka: true # eureka registry 등록 여부
    fetch-registry: true # registry에 있는 정보를 가져올지 여부
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
